### ISSUE TITLE
Sense doesn't display results correctly with Kibana 4.4.0

### ISSUE THREAD

**Issue by cstrzadala** [elastic/sense#112] opened 2016-02-18 19:32 UTC
When running a query via Sense in Kibana 4.4.0 against Elasticsearch 2.2.0, the results pane on the right doesn't display the `hits` correctly (See screenshot below).

<img width="1439" alt="screen shot 2016-02-18 at 10 36 37 am" src="https://cloud.githubusercontent.com/assets/88518/13155568/2e6df56e-d633-11e5-9752-213c0ca1086f.png">

**Comment by clintongormley** [comment] 2016-02-18 21:08
Duplicate of #104

**Closed by clintongormley** 2016-02-18 21:08 UTC
Labels: bug
