### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by Mainframe2008** [elastic/sense#111] opened 2016-02-16 13:46 UTC
We get the following error when we installed a self signed certificate:

Error connecting to 'https://server.mydomain.tld:9200/_search' :

Client request error: self signed certificate in certificate chain

Kibana 4.4.0
ES: 2.2.0
Shield 2.2.0
Sense 2.0.0-beta2

**Comment by vicvega** [comment] 2016-02-16 14:10
Maybe related to https://github.com/elastic/sense/issues/69

**Comment by Mainframe2008** [comment] 2016-02-16 14:41
It is. The supplied temp fix helped out.

**Comment by spalger** [comment] 2016-02-16 15:06
duplicate of https://github.com/elastic/sense/issues/69

**Closed by spalger** 2016-02-16 15:06 UTC
