### ISSUE TITLE
JSON view truncated

### ISSUE THREAD

**Issue by tylersmalley** [elastic/sense#127] opened 2016-03-18 21:26 UTC
When testing Sense in Kibana 4.5, the JSON body is limited to three lines. This is not present in Kibana 4.4.2.

On Ubuntu 14.04.4 with Chrome.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/40265/13892529/359760a2-ed15-11e5-89fd-682f2c917b70.gif)

**Comment by spalger** [comment] 2016-03-18 21:50
Duplicate of https://github.com/elastic/sense/issues/84

**Closed by spalger** 2016-03-18 21:50 UTC
Labels: bug
