### ISSUE TITLE
Fatal error on firing HEAD request in Sense UI

### ISSUE THREAD

**Issue by ahmadimt** [elastic/sense#110] opened 2016-02-14 06:54 UTC
I am getting Below error when firing HEAD request from sense UI. Anything else is working fine:
HEAD /{index_name}

![screenshot from 2016-02-13 22 59 22](https://cloud.githubusercontent.com/assets/10077189/13029006/80da1576-d2a5-11e5-8442-36c4a69b2f28.png)

**Comment by spalger** [comment] 2016-02-14 08:44
Duplicate of  https://github.com/elastic/sense/issues/76

**Closed by spalger** 2016-02-14 08:44 UTC
