### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/sense#81] opened 2015-11-16 16:34 UTC
Looks like the Black Theme has been removed from SENSE. This was used by many developers as well as for Demos.

**Comment by spalger** [comment] 2015-11-16 19:44
Duplicate of https://github.com/elastic/sense/issues/57

**Comment by gmoskovicz** [comment] 2015-11-16 19:45
Sorry, i was looking for "Black" rather than dark!

#57 +1

**Closed by spalger** 2015-11-16 19:44 UTC
